name: Import GPG key

on:
  workflow_call:

jobs:
  import:
    runs-on: docker

    steps:
      - name: Import GPG key
        id: import-gpg
        uses: https://github.com/crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.CI_GPG }}
          git_user_signingkey: true
          git_commit_gpgsign: true