name: Build Mix Assets

on:
  workflow_call:

jobs:
  build:
    runs-on: docker

    permissions:
      contents: write

    steps:
    - uses: https://code.itinerare.net/internal/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up node
      uses: https://github.com/actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'npm'

    - name: Install packages
      run: npm install

    - name: Run Mix
      run: npm run prod

    - name: Import GPG key
      uses: https://github.com/crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.CI_GPG }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit changes
      uses: https://github.com/EndBug/add-and-commit@v9
      with:
          pull: '--rebase --autostash'
          message: 'chore(deps): rebuild mix assets'
          default_author: github_actions
          author_name: ${{ vars.COMMITTER_NAME }}
          author_email: ${{ vars.COMMITTER_EMAIL }}