name: Run blade-formatter

on:
  workflow_call:

jobs:
  blade-formatter:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    concurrency:
      group: ci-blade-formatter-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v5
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Install packages
      run: npm install

    - name: Run blade-formatter
      run: npm run format

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
          message: 'refactor: fix blade formatting'
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com

