name: Set Auto-merge for Dependabot PRs

on:
  workflow_call:

jobs:
  set-automerge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set auto-merge
        if: ${{ startsWith(github.head_ref, 'dependabot/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --delete-branch "${{ github.head_ref }}"