name: Laravel Tests

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      db-name:
        required: true
        type: string

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
          image: mysql:8
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: ${{ inputs.db-name }}
          ports:
              - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: imagick

    - uses: actions/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run tests
      run: php artisan test
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
