name: Lint

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string

jobs:
  pint:
    uses: itinerare/github-actions/.github/workflows/pint.yml@main
    with:
      php-version: ${{ inputs.php-version }}
    concurrency:
      group: ci-lint-${{ github.head_ref }}

  blade-formatter:
    uses: itinerare/github-actions/.github/workflows/blade_formatter.yml@main
    concurrency:
      group: ci-lint-${{ github.head_ref }}

