name: Build Vite Assets

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v5
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Run Vite
      run: |
        npm install
        npm run build

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
          message: 'chore(deps): rebuild vite assets'
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
